export const books = [
    {
        id: 1,
        title: "To Kill a Mockingbird",
        description:
            "A novel about the serious issues of rape and racial inequality in the Deep South, seen through the eyes of a young girl.",
        cover: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
        author: "Harper Lee",
        rating: 4.8,
        category: "Classic Literature",
    },
    {
        id: 2,
        title: "1984",
        description:
            "A dystopian novel set in a totalitarian society under constant surveillance.",
        cover: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
        author: "George Orwell",
        rating: 4.7,
        category: "Dystopian",
    },
    {
        id: 3,
        title: "The Great Gatsby",
        description:
            "A critique of the American Dream set in the Roaring Twenties.",
        cover: "https://covers.openlibrary.org/b/id/7352168-L.jpg",
        author: "F. Scott Fitzgerald",
        rating: 4.5,
        category: "Classic Literature",
    },
    {
        id: 4,
        title: "Pride and Prejudice",
        description:
            "A romantic novel that explores issues of class, marriage, and morality.",
        cover: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
        author: "Jane Austen",
        rating: 4.6,
        category: "Romance",
    },
    {
        id: 5,
        title: "The Hobbit",
        description:
            "A fantasy novel following Bilbo Baggins’ adventure through Middle-earth.",
        cover: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
        author: "J.R.R. Tolkien",
        rating: 4.8,
        category: "Fantasy",
    },
    {
        id: 6,
        title: "The Catcher in the Rye",
        description:
            "A story about teenage alienation and angst told by the infamous Holden Caulfield.",
        cover: "https://covers.openlibrary.org/b/id/8228690-L.jpg",
        author: "J.D. Salinger",
        rating: 4.3,
        category: "Coming of Age",
    },
    {
        id: 7,
        title: "Moby-Dick",
        description:
            "A tale of obsession and revenge between a sea captain and a whale.",
        cover: "https://covers.openlibrary.org/b/id/7222261-L.jpg",
        author: "Herman Melville",
        rating: 4.2,
        category: "Adventure",
    },
    {
        id: 8,
        title: "The Alchemist",
        description:
            "A young shepherd travels to Egypt after having a recurring dream of finding treasure.",
        cover: "https://covers.openlibrary.org/b/id/8231857-L.jpg",
        author: "Paulo Coelho",
        rating: 4.7,
        category: "Philosophical Fiction",
    },
    {
        id: 9,
        title: "The Book Thief",
        description:
            "A young girl finds solace by stealing books during the horrors of Nazi Germany.",
        cover: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
        author: "Markus Zusak",
        rating: 4.6,
        category: "Historical Fiction",
    },
    {
        id: 10,
        title: "The Lord of the Rings",
        description: "An epic fantasy journey to destroy a powerful ring.",
        cover: "https://covers.openlibrary.org/b/id/7644783-L.jpg",
        author: "J.R.R. Tolkien",
        rating: 4.9,
        category: "Fantasy",
    },
    {
        id: 11,
        title: "The Kite Runner",
        description: "A story of friendship and redemption set in Afghanistan.",
        cover: "https://covers.openlibrary.org/b/id/8231779-L.jpg",
        author: "Khaled Hosseini",
        rating: 4.8,
        category: "Drama",
    },
    {
        id: 12,
        title: "The Fault in Our Stars",
        description: "Two teenagers with cancer fall in love.",
        cover: "https://covers.openlibrary.org/b/id/8168622-L.jpg",
        author: "John Green",
        rating: 4.5,
        category: "Young Adult",
    },
    {
        id: 13,
        title: "Harry Potter and the Sorcerer's Stone",
        description:
            "A boy discovers he’s a wizard and attends a magical school.",
        cover: "https://covers.openlibrary.org/b/id/7888784-L.jpg",
        author: "J.K. Rowling",
        rating: 4.9,
        category: "Fantasy",
    },
    {
        id: 14,
        title: "Life of Pi",
        description:
            "A young boy survives a shipwreck and shares a lifeboat with a tiger.",
        cover: "https://covers.openlibrary.org/b/id/7222247-L.jpg",
        author: "Yann Martel",
        rating: 4.4,
        category: "Adventure",
    },
    {
        id: 15,
        title: "The Silent Patient",
        description:
            "A woman stops speaking after committing a shocking act of violence.",
        cover: "https://covers.openlibrary.org/b/id/10435732-L.jpg",
        author: "Alex Michaelides",
        rating: 4.6,
        category: "Thriller",
    },
    {
        id: 16,
        title: "Becoming",
        description: "A memoir by the former First Lady of the United States.",
        cover: "https://covers.openlibrary.org/b/id/9359093-L.jpg",
        author: "Michelle Obama",
        rating: 4.9,
        category: "Biography",
    },
    {
        id: 17,
        title: "Educated",
        description:
            "A memoir about a woman who escapes her survivalist family and earns a PhD from Cambridge.",
        cover: "https://covers.openlibrary.org/b/id/9252021-L.jpg",
        author: "Tara Westover",
        rating: 4.8,
        category: "Memoir",
    },
    {
        id: 18,
        title: "Sapiens: A Brief History of Humankind",
        description: "A deep dive into the history of our species.",
        cover: "https://covers.openlibrary.org/b/id/9254155-L.jpg",
        author: "Yuval Noah Harari",
        rating: 4.9,
        category: "Non-Fiction",
    },
    {
        id: 19,
        title: "Atomic Habits",
        description:
            "An easy and proven way to build good habits and break bad ones.",
        cover: "https://covers.openlibrary.org/b/id/10587835-L.jpg",
        author: "James Clear",
        rating: 4.8,
        category: "Self-Help",
    },
    {
        id: 20,
        title: "Rich Dad Poor Dad",
        description:
            "Personal finance lessons from two very different father figures.",
        cover: "https://covers.openlibrary.org/b/id/11108130-L.jpg",
        author: "Robert T. Kiyosaki",
        rating: 4.7,
        category: "Finance",
    },
];

export const categories = [
    "Classic Literature",
    "Dystopian",
    "Romance",
    "Fantasy",
    "Coming of Age",
    "Adventure",
    "Philosophical Fiction",
    "Historical Fiction",
    "Drama",
    "Young Adult",
    "Thriller",
    "Biography",
    "Memoir",
    "Non-Fiction",
    "Self-Help",
    "Finance",
];
